login: &login
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: root
  password:

development:
  database: ab_admin_dummy_master
  <<: *login

test: &test
  database: ab_admin_dummy_master_test
  <<: *login

staging:
  database: ab_admin_dummy_master
  <<: *login

production:
  database: ab_admin_dummy_master
  <<: *login

cucumber:
  <<: *test